### ISSUE TITLE
State purpose of image

### ISSUE THREAD

**Issue by haz** [AI-Planning/docker-for-planners#2]
Strictly not for benchmarking, as it can be degrading to planner performance.

**Comment by JoanEspasa** [comment]
Unless all compared solvers are on a docker image, right?

**Comment by haz** [comment]
This is meant to be for the single unified image. Not on a per-planner basis. Main point is that this image _shouldn't_ be used to produce evaluations for publication -- the variability in performance makes it quite unreliable.

**Comment by haz** [comment]
Closing in lieu of the [new project](https://github.com/AI-Planning/planutils)
