### ISSUE TITLE
LAPKT Dockerfile

### ISSUE THREAD

**Issue by nirlipo** [AI-Planning/docker-for-planners#4]
LAPKT info:

- dockerfile: https://github.com/LAPKT-dev/docker-images/blob/master/lapkt-public/Dockerfile
- dockerhub: https://hub.docker.com/r/lapkt/lapkt-public/
- Readme and how to run: https://github.com/LAPKT-dev/docker-images/tree/master/lapkt-public

Let me know if you need help.

Cheers,

Nir

**Comment by haz** [comment]
Closing before I nix this repo. Lapkt should appear in multiple ways for the new [planutils](https://github.com/AI-Planning/planutils) repo.
