### ISSUE TITLE
Script for adding ENHSP

### ISSUE THREAD

**Issue by gabrielplicks** [AI-Planning/docker-for-planners#5]
I am not familiarized with Docker, therefore I didn't fork it and PR. But here is a script I use for downloading and installing ENHSP:

```
wget https://gitlab.com/enricos83/ENHSP-Public/-/archive/master/ENHSP-Public-master.zip
unzip ENHSP-Public-master.zip
rm ENHSP-Public-master.zip
mv ENHSP-Public-master/ enhsp
cd enhsp
./compile
./install
```

Hope it helps :D 
Very nice work btw!

Cheers,
Gabriel

**Comment by haz** [comment]
Thanks Gabriel!

Were you able to test this in the docker image? If you have docker installed, you can try the image directly by checking it out here: https://hub.docker.com/r/cjmuise/planutils

I should note that this repository is now defunct. I'll be removing it soon when the PR's are ported to the new more broader project: https://github.com/ai-planning/planutils

If you can provide a binary for enhsp (e.g., hosted somewhere online), then I can test it directly myself. If that works, then it would just be a matter of hosting the binary somewhere official, and creating a quick bit of json to configure things. More than happy to work through it with out, and it would be wonderful to have enhsp included!

**Comment by gabrielplicks** [comment]
I'm so sorry for the delay! I completely missed this open issue.

I did not try it within Docker. I never had any experience with it. If it helps, [here is a link](https://drive.google.com/open?id=1vWMouMDNjaT2pp-A9zx4kDziMcTuJobo) with an executable of ENHSP. Important to notice that I was only able to compile it using Java version 8 (recent Java versions did not work):

`sudo apt install openjdk-8-jre openjdk-8-jdk`

If you want to keep multiple Java versions, it is possible to change the Java version currently in use just for compiling and later change it back to the version you like to use. I use these commands to do that:

```
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

I might do some tests using the Docker image for the sake of learning. I will return to you in case I have something that I think might be useful :smile:

**Comment by haz** [comment]
Oy, I forgot about requiring Java for some planners. How about creating a new issue in the [planutils](https://github.com/AI-Planning/planutils) repo for ENHSP in particular? I think we're only a couple of days away from completing the [new manifest format](https://github.com/AI-Planning/planutils/pull/11) so you could hit the ground running there. Essentially you'd have an `install`, `uninstall`, and `run` bash scripts. The json config that goes with it would be trivial to do up.
